version: "3.7"
services:
  api:
    image: api
    build: ./api
    restart: always
    ports:
      - "8000:8000"
    env_file:
    - .env
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data/db
    ports:
      - "27017:27017"
    command: mongod --noauth
